apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: app
type: Opaque
stringData:
  username: admin
  password: password123
