apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: pankaj6262/nodeapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_USER
              value: admin
            - name: DB_PASS
              value: password123
            - name: DB_HOST
              value: mongodb    # Service name of MongoDB
            - name: DB_PORT
              value: "27017"
