name: CI/CD Pipeline

on:
  push:
  branches: ['main']
  pull_request:
  branches: ['main']

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    #checkout repo
    - name: checkout code
      uses: actions/checkout@v3

    # setup Nodejs
    - name: setup Node.js
      uses: actions/setup=node@v3
      with:
      node-version: '18'

    # Install dependencies
    - name: install dependencies
      run: npm install
      
    # Run tests
    - name: Run tests
      run: npm test || echo "No test found"

    # Run static analysis (sengrep)
    - name: Run semgrep
      uses: returnocorp/semgrep=action@v1
      with:
        config: "p/default"

    # Run lac scan (checkov)
    - name: Scan Terraform/laC
      uses: bridgecrewio/checkov-action@master
      with:
      directory: .

    # Scan Dockerfile with Trivy
      - name: Scan Dockerfile with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "config"
          scan-ref: ./Dockerfile
          exit-code: "1"   # Fail if vulnerabilities are found
          severity: "CRITICAL, HIGH
          
    # Docker Build
      - name: Build Docker image
        run: docker build -t pankaj6262/nodeapp:${{ github.run_number }} .
        run: docker build -t pankaj6262/nodeapp:latest .

          # Security scan with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: pankaj6262/nodeapp:${{ github.run_number }}
          exit-code: "1" # Fail if vulnerabilities found
          severity: "CRITICAL, HIGH"

      # Log in to Docker Hub
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Push image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodeapp:${{ github.sha }}
    
      
    
    
    





      
